apiVersion: v2
appVersion: 2.5.3
dependencies:
- condition: tarantool.enabled
  name: tarantool
  repository: ""
  version: 0.5.3
description: '[![Latest Release](https://gitlab.corp.mail.ru/tarantool/k8s/helm-chart-tqe/-/badges/release.svg)](https://gitlab.corp.mail.ru/tarantool/k8s/helm-chart-tqe/-/releases)  #
  Helm Chart TQE  ## Оглавление 1. [Описание](#описание) 2. [Зависимости](#зависимости)     1.
  [Чарты](#чарты)     2. [Внешние сервисы](#внешние-сервисы) 3. [Конфигурация](#конфигурация)
  4. [Запуск](#запуск)     1. [Порядок развертывания](#порядок-развёртывания) 5. [Известные
  неполадки](#известные-неполадки-и-возможные-решения)  ## Описание  Данный чарт позволяет
  развернуть [Tarantool QE][1].  В файле `Chart.yaml` указаны две версии: * version:
  версия helm-чарта * appVersion: самая свежая версия TarantoolQE, запущенная в чарте
  до релиза.  В результате разворачивания со всеми подключёнными необходимыми [зависимостями](#зависимости)
  мы получаем следующую инфраструктуру:  ``` etcd:     |     |---etcd-0     |---etcd-1     |---etcd-2  tarantool:     |     |---replicaset-router-0     |   |     |   |---router-0     |     |---replicaset-storage-0         |         |---storage-0  tcm:     |     |---tcm  tqe:     |     |---tqe-api-publisher     |---tqe-api-consumer
  ```  ## Зависимости    * [tarantool](https://gitlab.corp.mail.ru/tarantool/k8s/helm-chart-tarantool)  Для
  корректной работы TarantoolQE необходимо иметь подключение к [Tarantool][2].  Используемые
  чарты добавлены как подмодули git. Для их скачивания необходимо обновить git submodules:  ```bash
  git submodule update --init --recursive --remote ```  ## Конфигурация  Файл включает
  в себя конфигурацию как для tqe, так и для всех подчартов по схеме: ``` # конфиг
  для чарта tqe  tarantool:   # конфиг для чарта tarantool    etcd:   # конфиг для
  чарта etcd ```  Обратите внимание, что поля, не указанные в пользовательском values.yaml,
  будут взяты из внутренних файлов values.yaml. Таким образом, если не указать явным
  образом docker image для чарта tarantool, контейнер запустится на основе образа,
  указанного в charts/tarantool/values.yaml. Поля, существующие в `charts/tarantool/values.yaml`
  в блоке `config`, но не существующие в вашем конфиге, будут в него добавлены.  Пример
  рабочего файла values.yaml:  ``` tqe:   consumer:     replicas: 1   publisher:     replicas:
  1 credentials:   user: client   password: secret  affinity: nodeSelector: tolerations:
  []  # Если в этой секции указаны limits и/или requests, то их содержимое будет передано
  в чарт как есть resources:   limits:     cpu: "1"   requests:     cpu: "1"  tarantool:   affinity:   nodeSelector:   tolerations:
  []    image:     repository: registry.ps.tarantool.io/tarantool/message-queue-ee     pullPolicy:
  Always     tag: 2.0.0     command: ["tarantool"]   imagePullSecrets:     - name:
  ps-registry-auth    router:     replicasetCount: 1     replicaCount: 2     servicePort:
  3301     appPort: 3301     memoryLimit: 512Mi     cpuLimit: 200m   storage:     replicasetCount:
  1     replicaCount: 1     servicePort: 3301     appPort: 3301     memoryLimit: 512Mi     cpuLimit:
  200m     replicas: 1   # Common parameters for routers/storages   ttConfigEtcdPrefix:
  "/tqe"   ttConfigEtcdHttpRequestTimeout: 3   # Parameters for Trantool Cluster Manager   tcmServicePort:
  8081   tcmMemoryLimit: 512Mi   tcmCpuLimit: 200m   tcmServicePort: 8081    etcd:     enabled:
  true     replicaCount: 3     auth:       rbac:         create: false    config:     parameters:       credentials:         users:           admin:             password:
  ''secret-cluster-cookie''             roles: [super]           client:             password:
  ''secret''             roles: [super]           replicator:             password:
  ''secret''             roles: [replication]           storage:             password:
  ''secret''             roles: [sharding]       iproto:         advertise:           peer:             login:
  replicator           sharding:             login: storage       roles_cfg:         roles.metrics-export:           http:           -
  endpoints:             - format: prometheus               path: /metrics             listen:
  8081       sharding:         bucket_count: 30000       groups:         routers:           replication:             failover:
  manual           sharding:             roles:               - router           roles:             -
  app.roles.api         storages:           replication:             failover: election           sharding:             roles:
  [storage]           roles:             - app.roles.queue   tcm:     parameters:       http:         host:
  0.0.0.0         port: 8081        storage:         provider: etcd         etcd:           prefix:
  /tcm        security:         bootstrap-password: secret        cluster:         tt-command:
  tt          initial-settings:           clusters:             - name: Tarantool
  DB Cluster               id: 00000000-0000-0000-0000-000000000000               storage-connection:                 provider:
  etcd                 etcd-connection:                   prefix: /tcm                   username:
  client                   password: secret               tarantool-connection:                 username:
  "admin"                 password: secret  nodePorts:   - name: iproto     protocol:
  TCP     port: 3301     targetPort: iproto   - name: membership     protocol: UDP     port:
  3301     targetPort: membership  image:   repository: registry.ps.tarantool.io/tarantool/message-queue-ee   pullPolicy:
  Always   tag: 2.0.0  imagePullSecrets:   - name: ps-registry-auth ```  ## Запуск  Для
  запуска чарта настройте values.yaml как указано в главе [Конфигурация](#конфигурация)
  и запустите helm:  ```bash helm install <release name> <path to chart> ```  ###
  Порядок развёртывания  1. Инстансы etcd 2. Задача config job. Запускается, когда
  получает минимальный ответ от инстансов etcd, добавляет конфигурационный файл. 3.
  Инстансы tarantool и tcm. Запускаются, когда утилита etcdctl показывает, что в инстанс
  etcd успешно добавлен конфигурационный файл. 4. TQE gRPC (publisher, consumer) и
  gRPC офсет. Запускается, когда сервисы `<release name>-router` и `<release name>-storage`
  начинают отвечать.  ## Известные неполадки  | Проблема | Логи | Решение | |---|---|---|
  | Инстансы router и storage застряли в статусе `Pending`, gRPC в статусе `CrashLoopBackOff`
  | - | Не создались PV и PVC, неверно указан storage class в values | | Инстансы
  etcd застряли в статусе `Pending`, инстансы tarantool в статусе `CrashLoopBackOff`
  | - | Не создались PV и PVC. Либо неверно указан storage class, либо не удалились
  PVC с предыдущего запуска. | | Инстансы router и storage находятся в статусе CrashLoopBackOff
  | - | Вероятно, неверно задана конфигурация tarantool. Некоторые элементы конфига
  tarantool могут добавляться в текущий конфиг. Проверьте, нет ли лишних полей в `charts/tqe/charts/tarantool/values.yaml`
  в блоке `config:` |   [1]: https://www.tarantool.io/ru/queue-enterprise/ [2]: https://www.tarantool.io/ru/product/enterprise/  '
name: tqe
type: application
version: 2.5.3
