{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-admin-password"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "{{ .Release.name }}-admin-password") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $admSecret := (get $secretData "admpass") | default (randAlphaNum 32 | b64enc) }}
  admpass: {{ $admSecret | quote }}
